# Processing parameters
jetR: [0.4]
#betas: [1, 1.5, 2, 3]
betas: [1]
jet_range: [5,50]
# Initial detector-level binnings. Distributions are rebinned via configs before unfolding
n_pt_bins: 195
pt_limits: [5, 200]
n_lambda_bins: 160
lambda_limits: [0, 0.8]
n_rap_bins: 20            # just for fun, look at lambda distribution vs rapidity
rap_limits: [-0.5, 0.5]
branching_ratio: 0.0395
p_nevents: 7.98356e8
xsection_inel: 50.76
fRebinMass: 10
fMassRange: [1.72, 2.01]
fsigmaSignal: 2
jetptbinsMeasN: 10
fDmass: 1.864
fDsigma: 0.010
fsigmaBkg: [-9,-4,4,9]
fbkgtype: 0 # kExpo=0, kLin=1, kPol2=2, kNoBk=3, kPow=4, kPowEx=5
fUseRefl: False
jetptbinsMeasA: [2,3,4,5,6,8,10,14,20,30,50]
fptbinsJetFinalN: 4
jetptbinsFinalA: [2, 5, 7, 10, 20, 50, 60]
ptbinsDN: 11
ptbinsDA: [2, 3, 4, 5, 6, 7, 8, 10, 12, 16, 24, 36]
ptjet_cut: [7, 10, 10, 20, 20, 20, 20, 60, 60, 60, 60]
pt_dmeson_cut: [2, 2, 3, 5, 12, 16]
obs_bins: [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65]
# For extra verbose output in some functions
debug_level: 0

process_observables: ['ang']
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0

# SoftDrop setting (current same for all SD plots)
sd_zcut: 0.2    # multiplier
sd_beta: 0      # exponent on (deltaR / R)


###############################################################################
# Rebinning and unfolding parameters/configurations for angularity observables
ang:

  common_settings:
    xtitle: '#it{#lambda}_{#it{#beta}}^{#it{#kappa}=1}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{#lambda}_{#it{#beta}}^{#it{#kappa}=1}}'
    pt_bins_reported: [7, 10, 16]
    plot_overlay_list:
      - ['config_R0.4_B1', 'config_R0.4_B1.5', 'config_R0.4_B2', 'config_R0.4_B3']
      - ['config_R0.4_B1_SD', 'config_R0.4_B1.5_SD', 'config_R0.4_B2_SD', 'config_R0.4_B3_SD']
    max_reg_param: 10

  ############################################################################
  # Different R & beta configurations
  config_R0.4_B1:
    R: 0.4
    beta: 1
    pt_bins_truth:  [2, 5, 7, 10, 18, 50]
    pt_bins_det: [2, 5, 7, 10, 18, 50]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65]
    obs_max_reported: [0.55]
    obs_bins_det: [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65]
    obs_bins_det_sys_binning: [0, 0.05, 0.07, 0.09, 0.11, 0.13, 0.15, 0.17, 0.19, 0.20, 0.21,
                               0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.30, 0.31, 0.32, 0.33,
                               0.34, 0.35, 0.36, 0.37, 0.39, 0.41, 0.43, 0.45, 
                               0.47, 0.49, 0.56, 0.66, 0.75]
    reg_param:
      0.4: 3

  config_R0.4_B1.5:
    R: 0.4
    beta: 1.5
    pt_bins_truth:  [5, 7, 15, 30, 40, 50]
    pt_bins_det: [5, 7, 15, 30, 40, 50]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65]
    obs_max_reported: [0.55]
    obs_bins_det: [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65]
    obs_bins_det_sys_binning: [0, 0.025, 0.045, 0.055, 0.065, 0.075, 0.085, 0.095, 0.11, 0.12, 0.13,
                               0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.24, 0.25,
                               0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.33, 0.35, 0.37, 0.39,
                               0.41, 0.43, 0.57, 0.65]
    reg_param:
      0.4: 3

  config_R0.4_B2:
    R: 0.4
    beta: 2
    pt_bins_truth:  [5, 7, 15, 30, 40, 50]
    pt_bins_det: [5, 7, 15, 30, 40, 50]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65]
    obs_max_reported: [0.45]
    obs_bins_det: [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65]
    obs_bins_det_sys_binning: [0, 0.015, 0.025, 0.035, 0.045, 0.055, 0.065, 0.075, 0.085, 0.095, 
                               0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2, 0.21,
                               0.22, 0.23, 0.24, 0.25, 0.27, 0.29, 0.33, 0.48, 0.6]
    reg_param:
      0.4: 3

  config_R0.4_B3:
    R: 0.4
    beta: 3
    pt_bins_truth:  [5, 7, 15, 30, 40, 50]
    pt_bins_det: [5, 7, 15, 30, 40, 50]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65]
    obs_max_reported: [0.3]
    obs_bins_det: [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65]
    obs_bins_det_sys_binning: [0, 0.002, 0.006, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045,
                               0.5, 0.055, 0.6, 0.065, 0.07, 0.075, 0.08, 0.085, 0.09, 0.095, 0.1,
                               0.11, 0.12, 0.13, 0.14, 0.15, 0.17, 0.19, 0.21, 0.33, 0.5]
    reg_param:
      0.4: 3

  ############################################################################
  # Different R & beta configurations for SoftDrop
  config_R0.4_B1_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.4
    beta: 1
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13,
                     0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 
                     0.28, 0.3, 0.32, 0.34, 0.36, 0.38, 0.4, 0.42, 0.44, 0.47, 0.5, 0.55, 0.7, 0.8]
    obs_max_reported: [0.7]
    obs_bins_det: [0, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13,
                   0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 
                   0.28, 0.3, 0.32, 0.34, 0.36, 0.38, 0.4, 0.42, 0.44, 0.47, 0.5, 0.55, 0.7, 0.8]
    obs_bins_det_sys_binning: [0, 0.015, 0.025, 0.035, 0.045, 0.055, 0.065, 0.075, 0.085, 0.095, 
                               0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2, 0.21,
                               0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.29, 0.31, 0.33, 0.35, 0.37,
                               0.39, 0.41, 0.43, 0.45, 0.48, 0.51, 0.57, 0.68, 0.8]
    reg_param:
      0.4: 3

  config_R0.4_B1.5_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.4
    beta: 1.5
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.055, 0.06,
                     0.065, 0.07, 0.075, 0.08, 0.09, 0.1, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18,
                     0.19, 0.20, 0.22, 0.24, 0.26, 0.28, 0.30, 0.32, 0.34, 0.37, 0.4, 0.55, 0.75]
    obs_max_reported: [0.55]
    obs_bins_det: [0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.055, 0.06,
                   0.065, 0.07, 0.075, 0.08, 0.09, 0.1, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18,
                   0.19, 0.20, 0.22, 0.24, 0.26, 0.28, 0.30, 0.32, 0.34, 0.37, 0.4, 0.55, 0.75]
    obs_bins_det_sys_binning: [0, 0.003, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.045, 0.05, 0.055,
                               0.065, 0.07, 0.075, 0.085, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17,
                               0.18, 0.19, 0.21, 0.23, 0.25, 0.27, 0.29, 0.31,
                               0.33, 0.35, 0.38, 0.41, 0.57, 0.75]
    reg_param:
      0.4: 3

  config_R0.4_B2_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.4
    beta: 2
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.002, 0.004, 0.007, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045,
                     0.05, 0.055, 0.06, 0.065, 0.07, 0.075, 0.08, 0.09, 0.1, 0.12, 0.14, 0.16, 
                     0.18, 0.20, 0.22, 0.24, 0.27, 0.3, 0.35, 0.45, 0.65]
    obs_max_reported: [0.45]
    obs_bins_det: [0, 0.002, 0.004, 0.007, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045,
                   0.05, 0.055, 0.06, 0.065, 0.07, 0.075, 0.08, 0.09, 0.1, 0.12, 0.14, 0.16, 
                   0.18, 0.20, 0.22, 0.24, 0.27, 0.3, 0.35, 0.45, 0.65]
    obs_bins_det_sys_binning: [0, 0.001, 0.003, 0.006, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04,
                               0.045, 0.05, 0.055, 0.06, 0.065, 0.07, 0.075, 0.08, 0.085, 0.095, 0.11,
                               0.13, 0.15, 0.17, 0.19, 0.21, 0.23, 0.25, 0.28, 0.31, 0.37, 0.47, 0.65]
    reg_param:
      0.4: 3

  config_R0.4_B3_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.4
    beta: 3
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.001, 0.002, 0.004, 0.007, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04,
                     0.045, 0.05, 0.055, 0.06, 0.065, 0.07, 0.075, 0.08, 0.085, 0.09, 0.095, 0.1,
                     0.12, 0.14, 0.16, 0.18, 0.20, 0.22, 0.25, 0.35, 0.55]
    obs_max_reported: [0.35]
    obs_bins_det: [0, 0.001, 0.002, 0.004, 0.007, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04,
                   0.045, 0.05, 0.055, 0.06, 0.065, 0.07, 0.075, 0.08, 0.085, 0.09, 0.095, 0.1,
                   0.12, 0.14, 0.16, 0.18, 0.20, 0.22, 0.25, 0.35, 0.55]
    obs_bins_det_sys_binning: [0, 0.001, 0.003, 0.005, 0.008, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035,
                               0.04, 0.045, 0.05, 0.055, 0.065, 0.075, 0.085, 0.09, 0.095, 0.1, 0.11,
                               0.13, 0.15, 0.17, 0.19, 0.23, 0.27, 0.38, 0.55]
    reg_param:
      0.4: 3


###############################################################################
# Analysis & plotting parameters
file_format: ".pdf"
output_dir: "/Users/preeti/Analysis/analysisHF/AnalysisResults/ang/main_response/AngR04_ptbin1/"
roounfold_path: "/Users/preeti/Analysis/analysisHF/heppy/external/roounfold/roounfold-current/lib/libRooUnfold.so"

analysis_observable: 'ang'
do_unfolding: True
force_rebin: False
do_systematics: False
do_plot_final_result: True
do_plot_performance: False
figure_approval_status: 'Preliminary'

# Whether or not to use the previous preliminary result in final results
use_prev_prelim: False

systematics_list:
  - main
  - trkeff
  - prior1
  - prior2
  - truncation
  - binning
  - random_mass
  - fastsim_generator0
  - fastsim_generator1

# Paths to processing output, to be used for unfolding
main_data: ''
main_response: ''
trkeff_response: ''
#main_data_simulation: '/Users/preeti/Analysis/analysisHF/ang/main_response/AnalysisResults_fullMC.root'
main_data_simulation: '/Users/preeti/MC_758/AnalysisResultsFinal.root'

main_efffile: '/Users/preeti/Analysis/analysisHF/ang/reco_efficiency/D0JetRecoEff.root'

randmass_data: ''
randmass_response: ''
fastsim_response: ['/rstorage/alice/AnalysisResults/ang/287385/AnalysisResultsFinal.root',
                   '/rstorage/alice/AnalysisResults/ang/287386/AnalysisResultsFinal.root']

# Prior variation parameters
prior_variation_option: 1
prior1_variation_parameter: 0.5
prior2_variation_parameter: -0.5


